// BOOTH 상품에 쓰이는 표기와 한국·영문권에서 자주 쓰는 검색 표기를 연결합니다.
// terms는 실제 상품명에서 찾을 공식 표기, aliases는 사용자가 입력할 수 있는 표기입니다.
export const AVATAR_SEARCH_ALIASES = Object.freeze([
  { terms: ["ミルティナ", "Milltina"], aliases: ["miltina", "mirutina", "밀티나", "미루티나"] },
  { terms: ["海咲", "Misaki", "ミサキ", "みさき"], aliases: ["misaki", "미사키"] },
  { terms: ["ルルネ", "rurune"], aliases: ["lulune", "루루네", "룰루네", "르루네"] },
  { terms: ["しなの", "Shinano"], aliases: ["시나노"] },
  { terms: ["マヌカ", "Manuka"], aliases: ["마누카"] },
  { terms: ["桔梗", "Kikyo"], aliases: ["kikyou", "키쿄", "키쿄우"] },
  { terms: ["萌", "Moe"], aliases: ["모에"] },
  { terms: ["愛莉", "Airi"], aliases: ["아이리"] },
  { terms: ["セレスティア", "Selestia"], aliases: ["celestia", "세레스티아", "셀레스티아"] },
  { terms: ["Sio", "しお", "シオ"], aliases: ["shio", "시오"] },
  { terms: ["森羅", "Shinra"], aliases: ["신라"] },
  { terms: ["ラシューシャ", "Lasyusha"], aliases: ["rasyusha", "라슈샤"] },
  { terms: ["舞夜", "Maya"], aliases: ["마야"] },
  { terms: ["めいゆん", "MEIYUN"], aliases: ["meiyun", "메이윤", "메이윈"] },
  { terms: ["ライム", "Lime"], aliases: ["raimu", "라임"] },
  { terms: ["シフォン", "Chiffon"], aliases: ["shifon", "시폰", "쉬폰"] },
  { terms: ["ショコラ", "Chocolat"], aliases: ["chocolate", "shokora", "쇼콜라"] },
  { terms: ["まめひなた", "Mamehinata"], aliases: ["mame hinata", "마메히나타", "마메 히나타"] },
  { terms: ["キプフェル", "Kipfel"], aliases: ["kipuferu", "킵펠", "키프펠", "키푸페루"] },
  { terms: ["瑞希", "Mizuki"], aliases: ["미즈키"] },
  { terms: ["ルミナ", "LUMINA"], aliases: ["lumina", "rumina", "루미나"] },
  { terms: ["マリシア", "Marycia"], aliases: ["marishia", "마리시아"] },
  { terms: ["Lapwing"], aliases: ["랩윙", "랩핑"] },
  { terms: ["Robin", "ロビン"], aliases: ["로빈"] },
  { terms: ["竜胆", "Rindo"], aliases: ["rindou", "린도", "린도우"] },
  { terms: ["Grus", "グルス"], aliases: ["gurusu", "그루스"] },
  { terms: ["カリン", "Karin"], aliases: ["카린"] },
  { terms: ["狐雪", "Koyuki"], aliases: ["코유키"] },
  { terms: ["リーファ", "Leefa"], aliases: ["rifa", "리파"] },
  { terms: ["アッシュ", "Ash"], aliases: ["asshu", "애쉬"] },
  { terms: ["まりえる", "Mariel"], aliases: ["마리엘"] },
  { terms: ["薄荷", "Hakka"], aliases: ["하카"] },
  { terms: ["ウルフェリア", "Wolferia"], aliases: ["urufueria", "울페리아", "울퍼리아"] },
  { terms: ["ルーナリット", "Lunalitt"], aliases: ["runaritto", "루나릿", "루나리트"] },
  { terms: ["サフィー", "Sapphy"], aliases: ["safi", "사피"] },
  { terms: ["リア-アリス", "リアアリス", "RearAlice"], aliases: ["rear alice", "리아앨리스", "리어앨리스"] },
  { terms: ["ここあ", "Kokoa"], aliases: ["cocoa", "코코아"] },
  { terms: ["イメリス", "Imeris"], aliases: ["이메리스"] },
  { terms: ["ナユ", "Nayu"], aliases: ["나유"] },
  { terms: ["ホノカ", "Honoka"], aliases: ["호노카"] },
  { terms: ["プラチナ", "Platinum"], aliases: ["purachina", "플라티나", "플래티넘"] },
  { terms: ["ラスク", "Rusk"], aliases: ["rasuku", "라스크"] },
  { terms: ["京狐", "Kyoko"], aliases: ["kyouko", "쿄코", "쿄우코"] },
  { terms: ["水瀬", "Minase"], aliases: ["미나세"] },
  { terms: ["杏里", "Anri"], aliases: ["안리"] },
  { terms: ["ウユ", "Uyoo"], aliases: ["uyu", "우유"] },
  { terms: ["ネミア", "Nenmir"], aliases: ["nemia", "넨미르", "네미아"] },
  { terms: ["イェーナ", "Yena"], aliases: ["예나"] },
  { terms: ["リセ", "Lise"], aliases: ["rise", "리세"] },
  { terms: ["ルキフェル", "Lucifer"], aliases: ["rukiferu", "루키펠", "루시퍼"] },
  { terms: ["アル", "Alu"], aliases: ["aru", "아루"] },
  { terms: ["ハオラン", "Haolan"], aliases: ["hao lan", "하오란"] },
  { terms: ["狛乃", "Komano"], aliases: ["코마노"] },
  { terms: ["チセ", "Chise"], aliases: ["치세"] },
  { terms: ["メリノ", "Merino"], aliases: ["메리노"] },
  { terms: ["真冬", "Mafuyu"], aliases: ["마후유"] },
  { terms: ["あのん", "Anon"], aliases: ["아논"] },
  { terms: ["ミーシェ", "Mishe"], aliases: ["미셰", "미쉐"] },
  { terms: ["ソラハ", "Soraha"], aliases: ["소라하"] },
  { terms: ["ミント", "Mint"], aliases: ["민트"] },
  { terms: ["凪", "Nagi"], aliases: ["나기"] },
  { terms: ["幽狐族のお姉様", "Yuuko"], aliases: ["yuko", "유우코", "유코"] },
  { terms: ["むろむ", "Muromu"], aliases: ["무로무"] },
  { terms: ["Nardoragon"], aliases: ["nardo dragon", "나도래곤", "나르도래곤"] },
  { terms: ["Novabeast"], aliases: ["nova beast", "노바비스트"] },
  { terms: ["Rexouium"], aliases: ["렉소이움", "렉소윰"] },
  { terms: ["Hyenid"], aliases: ["하이에니드"] },
  { terms: ["Wickerbeast"], aliases: ["wicker beast", "위커비스트"] },
]);
